# Generated by Django 6.0.6 on 2026-07-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='poster_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='hero/images/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='hero/videos/'),
        ),
    ]
