# Generated by Django 6.0.6 on 2026-07-03 06:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_herosection_poster_image_file_herosection_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='heading',
            field=models.CharField(default='Pools shaped<br>around how you live', help_text='Use <br> for a line break.', max_length=300),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='poster_image_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
