# Generated by Django 6.0.6 on 2026-07-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0005_product_image1_product_image2_product_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
    ]
