# Generated by Django 6.0.6 on 2026-07-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0007_alter_galleryimage_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_prices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
