# Generated by Django 6.0.6 on 2026-07-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0008_product_size_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_type',
            field=models.CharField(choices=[('inches', 'Inches'), ('sizes', 'Sizes')], default='inches', max_length=10),
        ),
    ]
