# Generated by Django 6.0.6 on 2026-07-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0009_product_colors_product_variant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
