# Generated by Django 6.0.6 on 2026-07-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0010_herosection_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='poster_image',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='poster_image_file',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='video_url',
        ),
    ]
