# Generated by Django 6.0.6 on 2026-07-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0012_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('nozzle_inlet', 'Nozzles & Inlets'), ('waterblade', 'Water Blades'), ('cover_ladder', 'Pool Covers & Ladders'), ('lights', 'Underwater Pool Lights'), ('chemicals', 'Pool Chemicals'), ('pump_filter', 'Pumps & Filters'), ('skimmer', 'Pool Skimmers'), ('vacuum', 'Pool Vacuum'), ('drain', 'Main Drains'), ('grating', 'Overflow Gratings'), ('fountain', 'Pool Fountains'), ('heater', 'Pool Heaters'), ('controller', 'Pool Controllers'), ('tiles', 'Pool Tiles')], default='pool', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant_type',
            field=models.CharField(choices=[('inches', 'Inches (in)'), ('feet', 'Feet (ft)'), ('meter', 'Meter (m)'), ('sqft', 'Square Feet (sq ft)'), ('sizes', 'Custom Size')], default='inches', max_length=10),
        ),
    ]
