# Generated by Django 6.0.6 on 2026-07-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0013_alter_product_category_alter_product_variant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('nozzle_inlet', 'Nozzles & Inlets'), ('waterblade', 'Water Blades'), ('cover_ladder', 'Pool Covers & Ladders'), ('lights', 'Underwater Pool Lights'), ('chemicals', 'Pool Chemicals'), ('pump_filter', 'Pumps & Filters'), ('skimmer', 'Pool Skimmers'), ('vacuum', 'Pool Vacuum'), ('drain', 'Main Drains'), ('grating', 'Overflow Gratings'), ('fountain', 'Pool Fountains'), ('heater', 'Pool Heaters'), ('controller', 'Pool Controllers'), ('tiles', 'Pool Tiles'), ('cleaning', 'Pool Cleaning Equipment')], default='pool', max_length=20),
        ),
    ]
